name: PEP8

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, "3.13"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff --upgrade
    - name: utilities
      run: |
        ruff check --preview --statistics fink_filters/*.py
        ruff format --preview --check fink_filters/*.py
    - name: classification
      run: |
        ruff check --preview --statistics fink_filters/*/*.py
        ruff format --preview --check fink_filters/*/*.py
    - name: After the night filters
      run: |
        ruff check --preview --statistics fink_filters/*/filter_*/*.py
        ruff format --preview --check fink_filters/*/filter_*/*.py
    - name: Livestream filters
      run: |
        ruff check --preview --statistics fink_filters/*/livestream/*/*.py
        ruff format --preview --check fink_filters/*/livestream/*/*.py
